const predictedItemsList = [
  {
    id: '-1',
    name: 'Whiskey',
    averageUsagePerDay: 0.5,
    previouslyPurchasedQuantity: null,
    remainingQuantity: null,
    remainingQuantityPercentage: null,
    daysLeftUntilZeroQuantity: null,
  },
  {
    id: '0',
    name: 'Wine',
    averageUsagePerDay: 0.5,
    previouslyPurchasedQuantity: 1,
    remainingQuantity: 0,
    remainingQuantityPercentage: 0,
    daysLeftUntilZeroQuantity: 0,
  },
  {
    id: '1',
    name: 'Beer',
    averageUsagePerDay: 2,
    previouslyPurchasedQuantity: 6,
    remainingQuantity: 2,
    remainingQuantityPercentage: 25,
    daysLeftUntilZeroQuantity: 2,
  },
  {
    id: '10',
    name: 'Bread',
    averageUsagePerDay: 0.5,
    previouslyPurchasedQuantity: 2,
    remainingQuantity: 1,
    remainingQuantityPercentage: 50,
    daysLeftUntilZeroQuantity: 2,
  },
  {
    id: '2',
    name: 'Milk',
    averageUsagePerDay: 0.25,
    previouslyPurchasedQuantity: 4,
    remainingQuantity: 2,
    remainingQuantityPercentage: 75,
    daysLeftUntilZeroQuantity: 4,
  },
  {
    id: '3',
    name: 'Cheese',
    averageUsagePerDay: 0.1,
    previouslyPurchasedQuantity: 1,
    remainingQuantity: 1,
    remainingQuantityPercentage: 100,
    daysLeftUntilZeroQuantity: 6,
  },
];

export default predictedItemsList;
