# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Aisle5' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aisle5
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'Aisle5Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Aisle5-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aisle5-tvOS

  target 'Aisle5-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
